import { Product, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Categories', slug: 'all', icon: 'Grid' },
  { id: 'refrigeration', name: 'Refrigeration', slug: 'refrigeration', icon: 'Snowflake' },
  { id: 'washing-machine', name: 'Washing Machine', slug: 'washing-machine', icon: 'Droplets' },
  { id: 'refrigerator', name: 'Refrigerator', slug: 'refrigerator', icon: 'Box' },
  { id: 'electrical', name: 'Electrical / HVAC', slug: 'electrical', icon: 'Zap' },
  { id: 'refrigeration-tools', name: 'Refrigeration Tools', slug: 'refrigeration-tools', icon: 'Wrench' },
  { id: 'hvac-tools', name: 'HVAC Tools', slug: 'hvac-tools', icon: 'Hammer' },
  { id: 'accessories', name: 'Accessories & Consumables', slug: 'accessories', icon: 'ShieldCheck' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    productId: '1',
    category: 'Refrigeration',
    name: 'Filter Drier',
    brand: 'Multiple / Not specified',
    description: 'Refrigeration filter drier used in the liquid line to remove moisture and contaminants from the refrigerant circuit.',
    type: 'Refrigeration Spare Part',
    application: 'Refrigerators, air conditioners and refrigeration systems',
    variant: 'Multiple sizes/capacities',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-2',
    productId: '2',
    category: 'Refrigeration',
    name: 'R134a Cylinder Valve',
    brand: 'Not specified',
    description: 'Cylinder valve suitable for refrigerant R134a cylinders; exact connection/specification should be confirmed before quotation.',
    type: 'Cylinder Valve',
    application: 'Refrigerant cylinders / charging systems',
    variant: 'R134a; connection type to be confirmed',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-3',
    productId: '3',
    category: 'Refrigeration',
    name: 'NRV (Non-Return Valve)',
    brand: 'Multiple / Not specified',
    description: 'One-way valve designed to allow refrigerant or fluid flow in one direction and prevent reverse flow.',
    type: 'Refrigeration Valve',
    application: 'Refrigeration and HVAC systems',
    variant: 'Connection size/type varies',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-4',
    productId: '4',
    category: 'Washing Machine',
    name: 'Haier Semi-Automatic Timer – 45 Minute',
    brand: 'Haier',
    description: 'Mechanical/electromechanical timer for controlling the wash cycle duration of compatible Haier semi-automatic washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Haier semi-automatic washing machines',
    variant: '45-minute timer; model compatibility to be confirmed',
    hasVariants: false,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-5',
    productId: '5',
    category: 'Washing Machine',
    name: 'Haier Semi-Automatic Timer – 15 Minute',
    brand: 'Haier',
    description: 'Timer component for controlling the wash cycle duration of compatible Haier semi-automatic washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Haier semi-automatic washing machines',
    variant: '15-minute timer; model compatibility to be confirmed',
    hasVariants: false,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-6',
    productId: '6',
    category: 'Washing Machine',
    name: 'Samsung Timer – 15/35 Minute',
    brand: 'Samsung',
    description: 'Washing machine timer for compatible Samsung models, with 15-minute and 35-minute timing options as specified.',
    type: 'Washing Machine Spare Part',
    application: 'Samsung washing machines',
    variant: '15-minute / 35-minute timing; model compatibility to be confirmed',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-7',
    productId: '7',
    category: 'Refrigerator',
    name: 'LG Inverter PCB – Single Door',
    brand: 'LG',
    description: 'Original inverter control PCB intended for compatible LG single-door refrigerators.',
    type: 'Refrigerator Spare Part',
    application: 'LG single-door inverter refrigerators',
    variant: 'Original; model/PCB number required for compatibility',
    hasVariants: false,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-8',
    productId: '8',
    category: 'Refrigeration',
    name: 'Thermostat',
    brand: 'Multiple Brands',
    description: 'Temperature-control thermostat for refrigeration or cooling appliances. Exact type and temperature range depend on the application.',
    type: 'Temperature Control Component',
    application: 'Refrigerators and refrigeration equipment',
    variant: 'Multiple types and temperature ranges',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-9',
    productId: '9',
    category: 'Refrigeration',
    name: 'Outdoor Service Valve – Straight',
    brand: 'Multiple / Not specified',
    description: 'Straight-type outdoor/service valve used for refrigerant line isolation and service connections.',
    type: 'Refrigeration Valve',
    application: 'Air conditioners and refrigeration systems',
    variant: 'Straight configuration; size/connection varies',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-10',
    productId: '10',
    category: 'Refrigeration',
    name: 'Outdoor Service Valve – Bend',
    brand: 'Multiple / Not specified',
    description: 'Bend-type outdoor/service valve used for refrigerant line isolation and service connections where an angled configuration is required.',
    type: 'Refrigeration Valve',
    application: 'Air conditioners and refrigeration systems',
    variant: 'Bend configuration; size/connection varies',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-11',
    productId: '11',
    category: 'Electrical / HVAC',
    name: 'Running Capacitor – Totaline Pro-Tech',
    brand: 'Totaline Pro-Tech',
    description: 'Run capacitor designed for continuous-duty operation in compatible HVAC motors and compressor applications.',
    type: 'Capacitor',
    application: 'HVAC motors and condensing/compressor units',
    variant: 'Capacitance, voltage and terminal configuration vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-12',
    productId: '12',
    category: 'Electrical / HVAC',
    name: 'Running Capacitor – Hi-Tech Polymer',
    brand: 'Hi-Tech Polymer',
    description: 'Run capacitor for compatible condensing units and motor applications.',
    type: 'Capacitor',
    application: 'Condensing units and HVAC motors',
    variant: 'Capacitance, voltage and terminal configuration vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-13',
    productId: '13',
    category: 'Refrigerator',
    name: 'Original Refrigerator Timer',
    brand: 'Multiple / Not specified',
    description: 'Original replacement timer used to control a refrigerator\'s defrost or operating cycle, depending on the model.',
    type: 'Refrigerator Spare Part',
    application: 'Compatible refrigerators',
    variant: 'Timer type and model compatibility required',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-14',
    productId: '14',
    category: 'Washing Machine',
    name: 'Top Loading Automatic Drain Pump',
    brand: 'Multiple / Not specified',
    description: 'Drain pump for removing wastewater from compatible fully automatic top-loading washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Fully automatic top-loading washing machines',
    variant: 'Pump type, voltage and model compatibility vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-15',
    productId: '15',
    category: 'Washing Machine',
    name: 'Top Loading Washing Machine Inlet Valve',
    brand: 'Multiple / Not specified',
    description: 'Water inlet valve that controls the entry of water into compatible top-loading washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Top-loading washing machines',
    variant: 'Single/double inlet and voltage may vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-16',
    productId: '16',
    category: 'Washing Machine',
    name: 'Washing Machine Pulley Belt',
    brand: 'Multiple / Not specified',
    description: 'Drive belt used to transfer motor rotation to the drum or pulley assembly in compatible washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Compatible washing machines',
    variant: 'Belt size/profile varies by model',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-17',
    productId: '17',
    category: 'Washing Machine',
    name: 'Top Loading Automatic Washing Machine Hub',
    brand: 'Multiple / Not specified',
    description: 'Hub component used in the drive or agitator assembly of compatible automatic top-loading washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Automatic top-loading washing machines',
    variant: 'Hub design/model compatibility varies',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-18',
    productId: '18',
    category: 'Washing Machine',
    name: 'Drain Bellows – Semi-Automatic Washing Machine',
    brand: 'Multiple / Not specified',
    description: 'Flexible drain bellows/hose component used for wastewater drainage in compatible semi-automatic washing machines.',
    type: 'Washing Machine Spare Part',
    application: 'Semi-automatic washing machines',
    variant: 'Shape, length and inlet/outlet size vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-19',
    productId: '19',
    category: 'Refrigeration Tools',
    name: 'Single Manifold Gauge',
    brand: 'Multiple / Not specified',
    description: 'Single-gauge manifold set for pressure measurement and servicing of refrigeration or air-conditioning systems.',
    type: 'HVAC Service Tool',
    application: 'Refrigeration and air-conditioning servicing',
    variant: 'Refrigerant/gauge range and connection type vary',
    hasVariants: true,
    inStock: true,
    unit: 'Set',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-20',
    productId: '20',
    category: 'Electrical / HVAC',
    name: 'Contactor – Single Pole / Double Pole',
    brand: 'Multiple / Not specified',
    description: 'Electrical contactor used for switching compatible compressor, motor or HVAC loads.',
    type: 'Electrical Control Component',
    application: 'Air conditioners, refrigeration and electrical systems',
    variant: 'Single-pole / double-pole; coil voltage and current rating vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-21',
    productId: '21',
    category: 'HVAC Tools',
    name: 'LightPro Air-Fuel Torch – Harris',
    brand: 'Harris',
    description: 'Air-fuel torch for HVAC/refrigeration brazing and service work, subject to the applicable gas and tip configuration.',
    type: 'Brazing / Service Tool',
    application: 'HVAC and refrigeration installation/repair',
    variant: 'Torch configuration and tip options vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-22',
    productId: '22',
    category: 'Washing Machine',
    name: 'Samsung Safety Switch',
    brand: 'Samsung',
    description: 'Safety interlock switch for compatible Samsung washing machines, typically used to prevent operation when the required safety condition is not met.',
    type: 'Washing Machine Spare Part',
    application: 'Compatible Samsung washing machines',
    variant: 'Model/part-number compatibility required',
    hasVariants: false,
    inStock: true,
    unit: 'Piece',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-23',
    productId: '23',
    category: 'Refrigeration',
    name: 'Refrigerant Gas Cylinder',
    brand: 'Multiple / Not specified',
    description: 'Cylinder intended for storage or handling of refrigerant gas. Refrigerant type and cylinder specification must be confirmed before quotation.',
    type: 'Refrigerant Handling Equipment',
    application: 'Refrigeration and HVAC servicing',
    variant: 'Gas/refrigerant type and cylinder capacity vary',
    hasVariants: true,
    inStock: true,
    unit: 'Piece',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-24',
    productId: '24',
    category: 'Accessories & Consumables',
    name: 'Insulation Tape & Non-Stick Tape',
    brand: 'Multiple / Not specified',
    description: 'Tape products used for insulation, sealing, protection or service applications. Exact tape type depends on the intended use.',
    type: 'Consumable / Tape',
    application: 'Electrical, refrigeration and general service work',
    variant: 'Insulation tape / non-stick tape; width and length vary',
    hasVariants: true,
    inStock: true,
    unit: 'Roll',
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60'
  },
  {
    id: 'prod-25',
    productId: '25',
    category: 'Electrical / HVAC',
    name: 'Heavy Duty Multi-Strand Copper Wire',
    brand: 'Polycab / Finolex / Havells',
    description: 'High conductivity FR/FRLS copper wiring for heavy home appliances, air conditioners, and main power lines.',
    type: 'Electrical Wire',
    application: 'AC, Washing Machine, Refrigerator wiring',
    variant: '1.5 sq mm, 2.5 sq mm, 4 sq mm, 6 sq mm',
    hasVariants: true,
    inStock: true,
    unit: 'Roll',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&auto=format&fit=crop&q=60'
  }
];
